### ISSUE TITLE
Compilation error on ESP32-PICO (M5Stack Atom Lite)

### ISSUE THREAD

**Issue by DFughetta** [dennispg/esphome-fastcon#3]
Hi, I'm trying to install the basic configuration provided in the README on my M5Stack Kit Atom Lite (ESP32-PICO), but I get a compilation error.

Initially, I tried using my actual board configuration:
```
esp32:
  board: esp32dev
```

and I also set the mesh key retrieved from my Android phone, as per the very detailed instructions. However, I encountered the same compilation errors.

To rule out any issues caused by my modifications, I then tested the base configuration without changes, knowing it would not work with my specific device but wanting to verify if at least the default setup would compile correctly.

Here is my configuration:

```
esphome:
  name: brmesh
  friendly_name: BRmesh
  min_version: 2023.12.0
  name_add_mac_suffix: false


esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

esp32_ble_tracker:
esp32_ble_server:

# Source configuration
external_components:
  - source: github://dennispg/esphome-fastcon@main

# Controller configuration
fastcon:
  mesh_key: "12345678"    # Your mesh key in hex format

  # Optional parameters to control the advertisement protocol with their defaults:
  adv_interval_min: 0x20
  adv_interval_max: 0x40
  adv_duration: 50
  adv_gap: 10
  max_queue_size: 100

# Light configuration
light:
  - platform: fastcon
    id: living_room_light
    name: "Living Room Light"
    light_id: 1
```

When I try to compile, I get the following error:

```
In file included from src/esphome.h:21,
                 from src/main.cpp:3:
src/esphome/components/fastcon/fastcon_controller.h:22:49: error: 'light' has not been declared
             std::vector<uint8_t> get_light_data(light::LightState *state);
                                                 ^~~~~
src/esphome/components/fastcon/fastcon_controller.h:22:67: error: expected ',' or '...' before '*' token
             std::vector<uint8_t> get_light_data(light::LightState *state);
```

I'm compiling this configuration using Home Assistant OS running on a VM in an UNRAID server.

Is there something wrong with my configuration, or could this be a bug?
Thanks in advance for your help!
